### ISSUE TITLE
Invalid value for enum KeyCode

### ISSUE THREAD

**Issue by TheSneak** [Roblox/Core-Scripts#130] opened 2015-03-18 16:08 UTC
This occurs in the following places:
- ChatScript2
  - line 993
  - line 1162
  - line 1379

**Comment by einsteinK** [comment] 2015-03-19 16:35
Pretty sure that's an internal error, when getting the .KeyCode of an InputObject while
the key that's pressed doesn't have a proper KeyCode.
(Same error happens when setting .KeyCode = nil, or BasePart.FormFactor = nil)

**Comment by TheSneak** [comment] 2015-03-19 16:51
Nowhere in my rbxlx file is KeyCode found, nor FormFactor. 
This error seems to happen with certain non-US keyboard inputs. When it happens, it happens repeatedly to the same user. Following is my error log. Notice that the error occurred in two sets of three times, one at each line as described in the bug report:

```
Invalid value for enum KeyCode

Timestamp: 3/18/2015 12:32:45 PM
Player: anonplr528873
CoreGui.RobloxGui.CoreScripts/ChatScript2, line 1379

Timestamp: 3/18/2015 12:32:45 PM
Player: anonplr528873
CoreGui.RobloxGui.CoreScripts/ChatScript2, line 1162

Timestamp: 3/18/2015 12:32:45 PM
Player: anonplr528873
CoreGui.RobloxGui.CoreScripts/ChatScript2, line 993

Timestamp: 3/18/2015 12:32:58 PM
Player: anonplr528873
CoreGui.RobloxGui.CoreScripts/ChatScript2, line 1162

Timestamp: 3/18/2015 12:32:58 PM
Player: anonplr528873
CoreGui.RobloxGui.CoreScripts/ChatScript2, line 1379

Timestamp: 3/18/2015 12:32:58 PM
Player: anonplr528873
CoreGui.RobloxGui.CoreScripts/ChatScript2, line 993
```

**Comment by einsteinK** [comment] 2015-03-19 17:23
Yes, probably due to the "weird" keyboard, non-recognised keys are being used.
While trying to get the .KeyCode, it probably errors due to that reason.

**Comment by TheSneak** [comment] 2015-05-11 04:09
User Maelstrom in the roblox developer forum says this is caused by mac keyboards:
http://developer.roblox.com/forum/client-bug-reports/14730-what-s-up-with-the-chat-scripts#158667

**Comment by Quenty** [comment] 2015-05-11 13:13
I can confirm there is precedent for this glitch with invalid keycode enumerators being passed on Macs. 

TheSneak—off topic, but—what API are you using to track errors?

**Comment by TheSneak** [comment] 2015-05-11 13:17
I'm connecting to the Error event in ScriptContext, then passing those errors to a personal bug tracker via HttpService.

**Comment by einsteinK** [comment] 2015-05-11 15:27
I already gave a possible (and highly probable) explaination on another issue, I'll repeat it here:
```
> Instance.new'Part'.Shape=nil
17:03:59.764 - Invalid value for enum Shape
17:03:59.764 - Script 'Instance.new'Part'.Shape=nil', Line 1
17:03:59.765 - Stack End
```
That code is some code I wrote replicating the error that this issue is all about.
The error happens whenever you try to access _InputObject.KeyCode_.
(That is, if the key it should return isn't a valid one, as is the case with some key on mac).
My guess is that when this key is pressed, instead of setting the KeyCode to
the _Invalid_ one, it sets it internally to nil/null/void/whatever.
When indexing .KeyCode I assume it tries to set the KeyCode internally to nil, resulting to this error.

Of course I can't know for sure, this just seems a possible way of explaining this.

**Comment by MerelyRBLX** [comment] 2015-06-15 16:13
TrainedDoorman is seeing a bunch of these errors in GA.

![image](https://cloud.githubusercontent.com/assets/5466234/8164588/d23be6f0-133e-11e5-81f7-86333e065ee8.png)

**Comment by einsteinK** [comment] 2015-06-15 17:04
Seems like he has a lot of Mac users

**Comment by TrainedDoorman** [comment] 2015-06-15 17:11
These are events in the past 30 minutes. There are hundreds more than this. I can email them to anyone who wants to view more.

**Comment by einsteinK** [comment] 2015-06-15 17:13
Can you figure out who makes them happen, and which OS they use?
I assume this is mac-related, as all those errors happened in the past only for those players.

**Comment by BinaryResolved** [comment] 2016-04-20 01:37
@TheSneak @Quenty @MerelyRBLX @einsteinK @TrainedDoorman Is this still a problem for mac users?

**Comment by TrainedDoorman** [comment] 2016-04-20 02:11
@BinaryResolved  I still get a few along with other CoreGui issues.
![errors](https://cloud.githubusercontent.com/assets/12898347/14661435/93e1418a-067b-11e6-9b58-4a1e014fe6c3.png)

**Comment by BinaryResolved** [comment] 2016-04-20 02:29
@TrainedDoorman Thanks for the info, I don't own a mac but I will see what I can do.

**Comment by TheSneak** [comment] 2016-04-20 13:37
Note the varying sources of this error:

    CoreGui.RobloxGui.Modules.Settings.SettingsHub, line 1069
    CoreGui.RobloxGui.Modules.Chat, line 997    
    CoreGui.RobloxGui.Modules.Chat, line 1597
    CoreGui.RobloxGui.Modules.Chat, line 1036

**Comment by BinaryResolved** [comment] 2016-04-20 13:40
If you look at TrainedDoorman's picture you can see the same error happens in more then just those 4 lines. I am setting up a mac osx in virtualbox right now. Hopefully that will work and I can work on finding a fix.

**Comment by BinaryResolved** [comment] 2016-04-20 22:37
@TheSneak What OS version on mac are you using? E.G, Mavericks, Yosemite, El Capitan?

**Comment by TheSneak** [comment] 2016-04-20 22:40
My OS (Win 7) never causes the error. These errors are from the server logs of my games. I can't say which OS/version is responsible.

**Comment by BinaryResolved** [comment] 2016-04-20 22:44
Ok. I'm still setting up a osx environment, I'll keep you up to date. When I get started.

**Comment by TheSneak** [comment] 2016-04-20 22:45
On a tangent, if you get ROBLOX running in a VM, I'd be interested to know how. My attempts have been unsuccessful.

**Comment by BinaryResolved** [comment] 2016-04-20 22:47
Will do, all my attempts to get Yosemite running in a VM have failed. I may end up borrowing a friends mac.

**Comment by BinaryResolved** [comment] 2016-04-20 23:30
@TheSneak How far did you get to running ROBLOX on a VM? I got the osx installed and running, I got ROBLOX downloaded and installed, I'm just trying to figure out how to sort out the out of date drivers error. Is this how far you got?

**Comment by BinaryResolved** [comment] 2016-04-21 00:24
@TrainedDoorman Would it be possible for you to email me that list of errors in the coregui scripts?

**Comment by TheSneak** [comment] 2016-04-21 00:26
@BinaryResolved I got the VM running and installed roblox player. I could even run roblox player, but interacting with it with a mouse was impossible. Rendering glitches were out of control.

**Comment by BinaryResolved** [comment] 2016-04-21 00:29
@TheSneak Ah, I am still trying to get it to work. I won't need to do much with the mouse. All I need to be able to do is open up a baseplate in studio mode and try to find a fix. Did you have any trouble with your graphic drivers being out of date when running in VM?

**Comment by TheSneak** [comment] 2016-04-21 00:31
@BinaryResolved No, that wasn't a problem for me. The VM I used was Windows (Probably 7)

**Comment by BinaryResolved** [comment] 2016-04-21 00:44
@TheSneak Ok, I'm running VM on windows 10 but the osx graphics are utterly terrible when being ran in VM. I'm trying to clear them up a bit.

**Comment by BinaryResolved** [comment] 2016-04-21 20:52
I can't get it to run ROBLOX studio properly. I've tried everything I could find and do. Sorry that I couldn't help. Someone else that has access to a mac will have to debug and fix this. Sorry again.

**Comment by BinaryResolved** [comment] 2016-04-25 22:11
Might fix it, http://devforum.roblox.com/t/enum-keycode-deprecations/24415

**Comment by TheSneak** [comment] 2016-05-16 13:15
No, still not fixed.

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by ArceusInator** [comment] 2017-07-16 08:57
NIGGar FAggits MAke A Me HorRAnnyyyy

**Comment by cliffchapmanrbx** [comment] 2020-06-10 22:43
Hi there, thank you for your feedback. We're going to be closing this repository as we've chosed [the Roblox Dev Forum](https://devforum.roblox.com/) as our venue for developer feedback. Please feel free to migrate your feedback to a DevForum post if you feel it is still relevant.

**Closed by cliffchapmanrbx** 2020-06-10 22:43 UTC
