### ISSUE TITLE
When teleporting from studio, dialog does not respect CustomizedTeleportUI

### ISSUE THREAD

**Issue by Anaminus** [Roblox/Core-Scripts#19] opened 2014-05-28 21:06 UTC
_See [original issue](https://github.com/Anaminus/roblox-bug-tracker/issues/279) by @Anaminus_

---

Currently, when you attempt to teleport from the studio, a dialog pops up indicating that you can't do that. This dialog is displayed even when [TeleportService.CustomizedTeleportUI](http://anaminus.github.io/api/class/TeleportService.html#memberCustomizedTeleportUI) is true.

**Comment by BinaryResolved** [comment] 2016-04-18 22:04
@Anaminus Is this still occurring?

**Comment by slixxed** [comment] 2016-10-19 12:07
This issue was moved to slixxed/Core-Scripts#1

**Comment by slixxed** [comment] 2016-10-19 12:08
This issue was moved to slixxed/Core-Scripts#2

**Comment by GitBlox** [comment] 2016-10-19 12:47
This issue was moved to GitBlox/Core-Scripts#1

**Comment by ArceusInator** [comment] 2017-07-16 09:28
The ISsue IS MY doodDoo Hawl IS Malwdy

**Comment by cliffchapmanrbx** [comment] 2020-06-10 22:40
Hi there, thank you for your feedback. We're going to be closing this repository as we've chosed [the Roblox Dev Forum](https://devforum.roblox.com/) as our venue for developer feedback. Please feel free to migrate your feedback to a DevForum post if you feel it is still relevant.

**Closed as completed by cliffchapmanrbx** 2020-06-10 22:40 UTC
